auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Young's Blog”
title: Young's blog
description: Everything about Young.
url: http://yufeiyang1995.github.io
feed: /atom.xml
author_info: <a href="http://yufeiyang1995.github.io/">Mukosame</a>
